client_id = "7810a4ced6e55c404fe5a282f6d0b771"
application_url = "https://van-tion-capitol-favorite.trycloudflare.com"
name = "TrustWidget"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "sticky-cart-lcfrjjo0.myshopify.com"

[access_scopes]
scopes = "read_inventory,read_orders,read_products"

[auth]
redirect_urls = ["https://van-tion-capitol-favorite.trycloudflare.com/api/auth", "https://van-tion-capitol-favorite.trycloudflare.com/api/auth/callback"]

[app_proxy]
url = "https://van-tion-capitol-favorite.trycloudflare.com/api/proxy"
subpath = "tw-api"
prefix = "apps"

[webhooks]
api_version = "2024-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
