# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7810a4ced6e55c404fe5a282f6d0b771"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true
name = "TrustWidget"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_inventory,read_products"

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/inventory_levels/update"
  topics = [ "inventory_levels/update" ]

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[app_proxy]
url = "https://shopify.dev/apps/default-app-home/api/proxy"
subpath = "tw-api"
prefix = "apps"
